### ISSUE TITLE
Possible bug in palm

### ISSUE THREAD

**Issue by pwn1** [b-steve/palm#1]
Hi Ben,
I hope you're well. We are having a problem with palm with the function fit.twocamera. I hope you can help. 

If you unzip the attached, then:

> data=readRDS("baddata.rds")
> est=fit.twocamera(points=data$pts, cameras=data$planes, d=data$l, w=data$w, b=data$b, l=data$t, tau=data$C, R=data$R)
Error in matrix(0, nrow = self$n.points^2 - self$n.points, ncol = 2) : 
  invalid 'nrow' value (too large or NA)

I hope you can help.
Thanks 
Peter

[baddata.rds.zip](https://github.com/b-steve/palm/files/1964035/baddata.rds.zip)

**Comment by b-steve** [comment]
Hi Pete,

Yep, this looks like a minor bug. In the documentation it says the `points` argument should be "A vector (or single-column matrix) containing the distance along the transect that each detection was made", but it only seems to work if it is a single-column matrix and not if it is a vector.

I'll fix the bug soon, but in the meantime a workaround is to run the following code prior to calling `fit.twocamera()`:

`data$pts = matrix(data$pts, ncol = 1)`

I'll close this issue once I fix the bug...

Thanks for letting me know!

Ben

**Comment by pwn1** [comment]
Great, thanks. To be honest you don't need to fix it now we know the workaround!
All the best,
Pete

**Comment by b-steve** [comment]
May as well -- it's an easy fix, and someone else (probably me) would probably have been stumped by this in the future!
